### ISSUE TITLE
smartcontractkit/box-box doesn't exist. If you believe this is an error, please contact Truffle support.

### ISSUE THREAD

**Issue by KinuHero** [smartcontractkit/truffle-starter-kit#114]
When trying to run `truffle unbox smartcontractkit/box` 

I have the following error:

```
Starting unbox...
=================

✔ Preparing to download box
✖ Downloading
Unbox failed!
✖ Downloading
Unbox failed!
Error: Truffle Box at URL https://github.com:smartcontractkit/box-box doesn't exist. If you believe this is an error, please contact Truffle support.
    at /usr/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:42:1
    at Generator.throw (<anonymous>)
    at rejected (/usr/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:6:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Truffle v5.3.12 (core: 5.3.12)
Node v16.4.0
```
Node v16.4.0
Truffle v5.3.12

I was able to unbox other boxes such as react.

**Comment by PatrickAlphaC** [comment]
I'm able to reproduce this error. Thanks for making it.

**Comment by PatrickAlphaC** [comment]
We have created the issue here: https://github.com/trufflesuite/truffle/issues/4148

**Comment by cds-amal** [comment]
Apologies @PatrickAlphaC. There's a [PR awaiting approval](https://github.com/trufflesuite/truffle/pull/4145) before we publish. In the mean time, a workaround is to use v5.3.10:
``` console
npx truffle@5.3.10 unbox smartcontractkit/box sc
```

**Comment by PatrickAlphaC** [comment]
Thank you. We have a lot of content showing people how to use the unboxing feature with the original API. Excited for this to go through.

**Comment by cds-amal** [comment]
@PatrickAlphaC https://github.com/trufflesuite/truffle/releases/tag/v5.3.13

**Comment by KinuHero** [comment]
> Apologies @PatrickAlphaC. There's a [PR awaiting approval](https://github.com/trufflesuite/truffle/pull/4145) before we publish. In the mean time, a workaround is to use v5.3.10:
> 
> ```
> npx truffle@5.3.10 unbox smartcontractkit/box sc
> ```

thanks for answering. I think maybe this method would work in a clean install, in my machine it got stuck when it tried to install the early version of truffle. waited a few hours and cancelled. I will try with a clean image and report back.

**Comment by PatrickAlphaC** [comment]
This has been fixed in https://github.com/trufflesuite/truffle/releases/tag/v5.3.13. Thanks for making this issue!
