### ISSUE TITLE
Error: Truffle is currently using solc 0.6.6, but one or more of your contracts specify "pragma solidity ^0.8.0".

### ISSUE THREAD

**Issue by rfields1128** [smartcontractkit/truffle-starter-kit#127]
When I run

```bash
npm test
```
I get this error

![image](https://user-images.githubusercontent.com/38053428/157724427-13597bdf-efd8-4dde-abdd-37679855f52b.png)

The error comes from some @openzepplin node modules that specify "pragma solidity ^0.8.0". I was wondering if I was doing something wrong or if the repo needs to be updated somehow.

**Comment by rfields1128** [comment]
Duplicate of #122 

*facepalm* just realized this is already an issue... Sorry!

**Comment by cpascoli** [comment]
Workaround to avoid compilation error and get tests to pass is to downgrade openzeppelin contracts to version 3.3.0 in package.json:

`"@openzeppelin/contracts": "3.3.0",`
