### ISSUE TITLE
Error when running npm install

### ISSUE THREAD

**Issue by mcollarte** [smartcontractkit/truffle-starter-kit#96]
Hi team,

I've been struggling for days to be able to install the dependencies for this starter kit.
Whenever I run the "npm install" command right after successful unboxing I get the following error:
`npm ERR! code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/ethereumjs/ethereumjs-abi.git
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mariano Collarte\AppData\Local\npm-cache\_logs\2021-05-12T01_02_24_897Z-debug.log
`
I've setup the ssh account in my github profile and checked connection. This repository seems to be deprecated so I'm not sure why it is pulling it however the npm install fails and the node_modules folder is not being created.

Any help you can provide would be awesome!

Thanks

**Comment by PatrickAlphaC** [comment]
Thanks for making this issue. Could you try:

1. Installing `yarn` and then running `yarn` instead of `npm install`? https://classic.yarnpkg.com/en/docs/install/#mac-stable
2. Could you run the following 

```
mkdir new-project
cd new-project
truffle unbox smartcontractkit/box
yarn
```

**Comment by mcollarte** [comment]
Thanks Patrick for the quick response!

That seemed to work (though I got a lot of warnings and some errors in the process) however now I do see the node_modules folder in my project.
Also, I was getting a timeout error fetching packages which I was able to resolve with the following command:
yarn install --network-timeout 1000000000

Any idea why the npm install failed? Would you recommend yarn going forward?

Thanks!

**Comment by PatrickAlphaC** [comment]
Awesome! Glad it worked!

I'm not sure...  I've found yarn to be much more reliable on average over npm.

**Comment by PatrickAlphaC** [comment]
Closing as this is all set.
